name: Blackfire Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # hvert 5. minut
  workflow_dispatch:       # gør det muligt at køre manuelt

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Tjek repo ud
        uses: actions/checkout@v3

      - name: Sæt Python op
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer afhængigheder
        run: pip install requests beautifulsoup4

      - name: Kør script
        run: python blackfire_monitor.py
