name: Test Cron Every 5 Minutes

on:
  schedule:
    - cron: '*/5 * * * *'  # hvert 5. minut
  workflow_dispatch:

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Check ud repo
        uses: actions/checkout@v3

      - name: Tjek Python version
        run: python --version

      - name: Echo test
        run: echo "Workflow kører - $(date -u)"
